"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory\
[](fg:lavender) \
$git_branch"""
palette = 'catppuccin_mocha'
add_newline = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
style = "fg:lavender"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = ""
format = '[[$symbol $branch ](fg:purple)[>](fg:lavander) ]($style)'

[git_status]
style = "bg:purple"
format = '[[($all_status$ahead_behind )](fg:base bg:purple)[](fg:lavender)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:lavander)'
error_symbol = '[](bold fg:purple)'
vimcmd_symbol = '[](bold fg:yellow)'
vimcmd_replace_one_symbol = '[](bold fg:peach)'
vimcmd_replace_symbol = '[](bold fg:peach)'
vimcmd_visual_symbol = '[](bold fg:purple)'

