import = [
"~/.config/Alacritty/catppuccin-macchiato.toml"
]

[env]
term = "xterm-256color"

[window]
dynamic_padding = true
startup_mode = "Maximized"
opacity = 1.0

[terminal]
osc52 = "CopyPaste"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular"}
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold"}
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic"}
bold_italic = { family = "CaskaydiaMono Nerd Font", style = "Bold Italic"}

size = 14.0
